## NumPy

In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## NumPy Array(ndarray)

In [6]:
np.array([1, 2, 3])

array([1, 2, 3])

In [7]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# NumPy type -- int64
matrix = np.array([[1 ,2, 3],[4, 5, 6], [7, 8, 9]])

In [17]:
type(matrix[0][0])

numpy.complex128

In [10]:
# NumPy type -- complex
matrix = np.array([[1 ,2, 3],[4, 5, 6], [7, 8, 9]], dtype = complex)

In [11]:
type(matrix[0][0])

numpy.complex128

In [18]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [19]:
# よく使うdtype -- usigned int 8bit
ndarray = np.array([1, 2, 3], dtype = np.uint8)

In [20]:
ndarray

array([1, 2, 3], dtype=uint8)

In [15]:
# よく使うdtype -- float
ndarray = np.array([1, 2, 3], dtype = np.float32)

In [16]:
ndarray

array([1., 2., 3.], dtype=float32)

In [18]:
#タイプ変更
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

## ndarrayの演算

In [24]:
array1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
array2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [21]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
array1 - array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
array1 * array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [28]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [29]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
#要素数が違っても演算できる、自動で補ってくれる - Broadcasting
array1 = np.array([[1, 2, 3]])
array2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [33]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [34]:
ndarray = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [35]:
ndarray * 3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

## Shape

In [22]:
ndarray = np.array([[1, 2],[3, 4],[5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
#行列の数を確認(タプルの形で返ってくる) - 行列を作成したら、まず確認するようにする
ndarray.shape

(3, 2)

In [24]:
#shapeを変更する(要素の数があっていること)
ndarray.reshape(2 ,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [26]:
#まだ行列になっていない（ベクトルの形　一次元） shapeに注意
print(ndarray1)

[1 2 3]


In [27]:
print(ndarray1.shape)

(3,)


In [28]:
#行列の1行目(二次元の1行目)
print(ndarray2)

[[1 2 3]]


In [29]:
print(ndarray2.shape)

(1, 3)


In [30]:
#expand_dims - 次元(rank)を増やす(先頭)
expand_dims1= np.expand_dims(ndarray1, axis = 0)
expand_dims1

array([[1, 2, 3]])

In [32]:
#expand_dims - 次元(rank)を増やす
expand_dims2= np.expand_dims(ndarray1, axis = 1)
expand_dims2

array([[1],
       [2],
       [3]])

In [33]:
expand_dims2.shape

(3, 1)

In [34]:
#expand_dims - 次元(rank)を増やす（最後）
expand_dims2= np.expand_dims(ndarray1, axis = -1)
expand_dims2

array([[1],
       [2],
       [3]])

In [35]:
expand_dims2.shape

(3, 1)

In [36]:
#squeeze - 次元(rank)を減らす
np.squeeze(expand_dims2)

array([1, 2, 3])

In [37]:
np.squeeze(expand_dims2).shape

(3,)

In [40]:
#flatten - 1次元にする
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [41]:
ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
ndarray.shape

(3, 3)

In [44]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Indexing

In [45]:
ndarray = np.array([1, 2, 3, 4])

In [46]:
ndarray

array([1, 2, 3, 4])

In [47]:
ndarray[0]

1

In [48]:
ndarray[-1]

4

In [49]:
#多次元
ndarray = np.array([[1, 2],[3, 4],[5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
ndarray[0]

array([1, 2])

In [51]:
ndarray[0][1]

2

In [52]:
ndarray[0,1]

2

## Slicing

In [78]:
#１次元
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [79]:
#[N:M] N以上M未満
ndarray[1:3] #1以上３未満

array([2, 3])

In [80]:
ndarray[:2] #N省略 - [0]からM未満

array([1, 2])

In [81]:
ndarray[1:] #M省略 - Nから最後まで

array([2, 3, 4])

In [82]:
#マイナス値指定
ndarray[-2:] #最後から−２、から最初

array([3, 4])

In [83]:
ndarray[:-2] #最初から、最後からー２

array([1, 2])

In [84]:
#all
ndarray[:]

array([1, 2, 3, 4])

In [85]:
#多次元
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
ndarray[:3] #行 - 最初から[3]まで / 列 - 指定なし

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
#行も列もSlicingしたい場合は１つのスクウェア・ブラケット[]の中に指定する
#行指定が先
ndarray[:3, 2:] #行　 - 最初から[3]まで / 列 - [2]から最後まで

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [103]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [104]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [105]:
#下記の書き方だと常に行に対してしかSlicingしないので注意
#始めにndarrayの行の最初から[3]まで
#次に、上記に対して行の[2]から最後まで
ndarray[:3][2:]

array([[ 9, 10, 11, 12]])

In [106]:
ndarray[:, 2:] #行は全部取る、列は[2]から最後まで取る

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

## np.arange(Start, Stop, Step)

In [131]:
#リスト作成 Start以上、Stop未満、Step間隔(プラス値は昇順、マイナス値は降順)
#Stepがわかっている場合はこれを使用する

#0以上５未満を１の間隔で -> 0,1,2,3,4
np.arange(0, 5, 1) 

array([0, 1, 2, 3, 4])

In [121]:
#StartとStepは省略可(０始まり１間隔)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.arange(3, 100, 7)

array([ 3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94])

In [123]:
#range()と同じ使い方でOK
list(range(3, 100, 7))

[3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94]

In [126]:
#降順(StartとStopの値に注意)
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [127]:
np.arange(100, 10, -5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

## np.linspace(Start, Stop, Num)

In [132]:
#linearの略
#Start以上Stop以下の数をNum個で区切る
#Stop以下、つまりStopを含むので注意
#Stepは不明だが、取り出したい個数はわかっている場合に使用する

#0以上１０以下を１１個に区切る
np.linspace(0 ,10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [130]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## np.logspace(Start, Stop, Num)

In [137]:
#Num=50

#10の０乗(1)から１０の３乗(1000)までの値を１０個取ってくる、それで１０を累乗する
#10の０乗、10の0.3333...乗 、１０の0.666...乗、 ... 10の3乗
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [134]:
#linspaceとの違い
#0から10までを10等分する
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [138]:
10 ** 0.3333

2.1542693374042363

In [139]:
#endpointをFalseに指定してStop未満とすることが可能(logspace()にもlinspace()にも指定できる)
np.linspace(0, 3, 10, endpoint = False)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [141]:
np.logspace(0, 3, 10, endpoint = False)

array([  1.        ,   1.99526231,   3.98107171,   7.94328235,
        15.84893192,  31.6227766 ,  63.09573445, 125.89254118,
       251.18864315, 501.18723363])

## np.zeros(shape)

In [3]:
#要素が全部０
#データは不明だが箱だけ欲しい、といった場合に使用する
#shapeはtumple形式
shape = (3, 4) #3行４列
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
#shapeではなくintだと１次元
np.zeros(3)

array([0., 0., 0.])

## np.ones(shape)


In [6]:
#要素が全部１
#使い方はzerosと同じ
shape = (5,4)
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [11]:
#defaultの値をセットすることができる
np.ones((5, 4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

## np.eye()

In [12]:
#NxNの単位行列（対角成分が全て１の正方行列）
#eye - I Identify matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## np.randomで乱数の生成

### np.random.rand()

In [27]:
#単純に乱数(疑似乱数 pseudo random)を生成する
#サンプリングする、AIをtrainするときにデータを区切る　・・・
#毎回0から１の間で違う値が生成される
np.random.rand()

0.414056193273836

In [26]:
#引数を入れるとndarrayを返す
np.random.rand(3, 4)

array([[0.7763589 , 0.11192996, 0.25286433, 0.1051058 ],
       [0.13318863, 0.73460719, 0.87124996, 0.81208141],
       [0.11324642, 0.79479411, 0.2779643 , 0.85291245]])

## np.random.seed

In [64]:
#再現性を持たせることができる
#なるべくつける
#JupyterLabの場合、cellが変わると乱数も変わるので注意
np.random.seed(1)
np.random.rand()

0.417022004702574

In [33]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [34]:
np.random.rand()

0.7203244934421581

### np.random.randn()

In [37]:
#標準正規分布からランダムに値を取る
np.random.randn()

0.8654076293246785

In [38]:
np.random.randn(3, 4)

array([[-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 ],
       [-0.24937038,  1.46210794, -2.06014071, -0.3224172 ],
       [-0.38405435,  1.13376944, -1.09989127, -0.17242821]])

In [39]:
np.random.randn(10, 10)

array([[-0.87785842,  0.04221375,  0.58281521, -1.10061918,  1.14472371,
         0.90159072,  0.50249434,  0.90085595, -0.68372786, -0.12289023],
       [-0.93576943, -0.26788808,  0.53035547, -0.69166075, -0.39675353,
        -0.6871727 , -0.84520564, -0.67124613, -0.0126646 , -1.11731035],
       [ 0.2344157 ,  1.65980218,  0.74204416, -0.19183555, -0.88762896,
        -0.74715829,  1.6924546 ,  0.05080775, -0.63699565,  0.19091548],
       [ 2.10025514,  0.12015895,  0.61720311,  0.30017032, -0.35224985,
        -1.1425182 , -0.34934272, -0.20889423,  0.58662319,  0.83898341],
       [ 0.93110208,  0.28558733,  0.88514116, -0.75439794,  1.25286816,
         0.51292982, -0.29809284,  0.48851815, -0.07557171,  1.13162939],
       [ 1.51981682,  2.18557541, -1.39649634, -1.44411381, -0.50446586,
         0.16003707,  0.87616892,  0.31563495, -2.02220122, -0.30620401],
       [ 0.82797464,  0.23009474,  0.76201118, -0.22232814, -0.20075807,
         0.18656139,  0.41005165,  0.19829972

In [40]:
np.random.randn(3, 4, 5)

array([[[-1.61577235,  1.12141771,  0.40890054, -0.02461696,
         -0.77516162],
        [ 1.27375593,  1.96710175, -1.85798186,  1.23616403,
          1.62765075],
        [ 0.3380117 , -1.19926803,  0.86334532, -0.1809203 ,
         -0.60392063],
        [-1.23005814,  0.5505375 ,  0.79280687, -0.62353073,
          0.52057634]],

       [[-1.14434139,  0.80186103,  0.0465673 , -0.18656977,
         -0.10174587],
        [ 0.86888616,  0.75041164,  0.52946532,  0.13770121,
          0.07782113],
        [ 0.61838026,  0.23249456,  0.68255141, -0.31011677,
         -2.43483776],
        [ 1.0388246 ,  2.18697965,  0.44136444, -0.10015523,
         -0.13644474]],

       [[-0.11905419,  0.01740941, -1.12201873, -0.51709446,
         -0.99702683],
        [ 0.24879916, -0.29664115,  0.49521132, -0.17470316,
          0.98633519],
        [ 0.2135339 ,  2.19069973, -1.89636092, -0.64691669,
          0.90148689],
        [ 2.52832571, -0.24863478,  0.04366899, -0.22631424,
          1

In [41]:
#標準ではない任意の正規分布から値を取る
np.random.normal(0, 1)

-0.2873078634760189

In [42]:
np.random.normal(10, 1)

10.680069839878104

### np.random.randint(low, high, size)

In [43]:
#ランダムなintegerの値を取る
#low以上high未満の値をsizeのndarrayで返す
np.random.randint(10, 100, (2, 3))

array([[98, 86, 92],
       [21, 46, 26]])

In [50]:
#low以外は省略可
np.random.randint(10)

3

### np.random.choice(ndarray)

In [63]:
#指定したndarray(list)からランダムな値を取ってくる
#ランダムなindexをchoiceで作り、それで値を取ってくる、みたいなときに使用する
a = np.arange(0, 10)
np.random.choice(a)

4

## 統計量を求める

In [66]:
#標準正規分布から乱数を生成する
#平均０、分散１の正規分布からランダムに値を抽出
std_norm = np.random.randn(5, 5)
std_norm

array([[ 0.15851488,  0.87341823, -0.11138337, -1.03803876, -1.00947983],
       [-1.05825656,  0.65628408, -0.06249159, -1.73865429,  0.103163  ],
       [-0.62166685,  0.27571804, -1.09067489, -0.60998525,  0.30641238],
       [ 1.69182613, -0.74795374, -0.58079722, -0.11075397,  2.04202875],
       [ 0.44752069,  0.68338423,  0.02288597,  0.85723427,  0.18393058]])

In [67]:
#最大値
std_norm.max()

2.042028746998981

In [68]:
np.max(std_norm)

2.042028746998981

In [71]:
#最小値
std_norm.min()

-1.7386542949953838

In [72]:
np.min(std_norm)

-1.7386542949953838

In [77]:
#最大値のindex
#要素が1行の時のindexを返す
std_norm.argmax()

19

In [81]:
std_norm.flatten()[19]

2.042028746998981

In [82]:
#最小値のindex
#要素が1行の時のindexを返す
std_norm.argmin()

8

In [84]:
std_norm.flatten()[8]

-1.7386542949953838

In [85]:
#平均を求める
std_norm.mean()

-0.019112603830767315

In [88]:
#中央値を求める
#書き方注意
#値を並べ替えるので平均値より時間がかかる
#外れ値に強い
np.median(std_norm)

0.022885974814366744

In [95]:
#中央値と平均値の計算時間を比較してみる
import time
a = np.random.randn(1000, 1000)
before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()
print('median {} sec'.format(after_median - before))
print('mean   {} sec'.format(after_mean - after_median))

median 0.03655052185058594 sec
mean   0.008239984512329102 sec


In [97]:
#標準偏差σ(std: standard deviation)を取得する
np.std(std_norm)

0.8711286088495804

In [102]:
#行ごと、列ごとの統計量を取得する
#axis: 0（列）
std_norm.max(axis=0)

array([1.69182613, 0.87341823, 0.02288597, 0.85723427, 2.04202875])

In [103]:
#axis: 1(行)
std_norm.max(axis=1)

array([0.87341823, 0.65628408, 0.30641238, 2.04202875, 0.85723427])

### 数学で使う便利関数

In [104]:
#平方根 square root
np.sqrt([1, 2, 3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [107]:
#階乗の指数 (logarithm)
#defaultの底はネイピア数
x = np.linspace(1, 10, 10)
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [110]:
#指数関数 exponential funciton
#ネイピア数の指数
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [112]:
#ネイピア数
np.e

2.718281828459045

In [114]:
#合計 summation
array = np.arange(1, 11)
np.sum(array)

55

In [115]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
ndarray = array.reshape(2, 5) #arange -> reshape
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [122]:
#列ごとの合計
np.sum(ndarray, axis=0)

array([ 7,  9, 11, 13, 15])

In [123]:
#行ごとの合計
np.sum(ndarray, axis=1)

array([15, 40])

In [128]:
#絶対値 absolute value
array = np.arange(-10, 0)
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [129]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Nan: Not a Number

In [130]:
np.log(-100)

nan

In [131]:
np.nan

nan

In [132]:
#nanが原因でエラーが出た場合、floatのエラーとなる
#float関連のエラーが出てきたら、np.nanを疑ってみるのが良い
type(np.nan)

float

In [134]:
a = None
a is None

True

In [137]:
#NaNかどうかをチェックする
#NumPyのNaNチェックは必ずnp.isnanを使う
np.isnan(np.log(-100))

True

### その他便利関数

### np.clip(ndarray, min, max)

In [146]:
#ndarrayにて、min未満の数値はminに、max以上の値はmaxに変換する
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [144]:
1e-4

0.0001

## numpy arrayのcondition

### np.where(condition, a, b)

In [153]:
#conditionがtrueの場合はa、falseの場合はbに変換する
#戻り値はtupleで返る
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [154]:
#condition以外は省略可
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [165]:
#filterとなっている(filterの一般的な使い方。whereよりもこっち)
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [157]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [159]:
array[array > 3]

array([4, 5, 6, 7, 8, 9])

In [161]:
#戻り値はtuple
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [163]:
#arrayだけを取り出したい
result, = np.where(array > 3)
result

array([4, 5, 6, 7, 8, 9])

In [167]:
#多次元
ndarray = array.reshape(2, 5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [168]:
#戻り値注意(2x５の形は保てない)
ndarray[ndarray > 3]

array([4, 5, 6, 7, 8, 9])

In [169]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [170]:
#(condtion).all
#ndarrayの全ての要素がconditionを満たすか
(ndarray > 3).all()

False

In [172]:
#(condition).any
#ndarrayの要素が１つでもconditionを満たすか
(ndarray > 3).any()

True

In [177]:
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [173]:
#列ごとの判定
(ndarray > 3).any(axis=0)

array([ True,  True,  True,  True,  True])

In [182]:
#行ごとの判定
(ndarray > 3).any(axis=1)

array([ True,  True])

### np.unique()

In [186]:
#ndarrayのユニークな値だけを返す
array = np.array([1, 1, 2, 3, 4, 2 ,3, 4, 5])
array

array([1, 1, 2, 3, 4, 2, 3, 4, 5])

In [187]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [188]:
#return_countsを指定すると、その値がいくつあるかを返す
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

### np.bincount()

In [189]:
#0, 1, 2, 3 ... の各カウント数を返す
np.bincount(array)

array([0, 2, 2, 2, 2, 1])

## 統合と転置

### np.concatenate()

In [190]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [195]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [198]:
#縦に結合(defalut: axis=0)
np.concatenate([ndarray_even, ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [197]:
#横に結合
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

### np.stack()

In [206]:
#新たなaxisを作成してデータを連結(defalut: axis=0)
np.stack([ndarray_even, ndarray_odd])

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [202]:
stacked_array = _

In [203]:
stacked_array

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [205]:
stacked_array.shape

(2, 3, 3)

In [208]:
stacked_array = np.stack([ndarray_even, ndarray_odd], axis = 1)
stacked_array

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]],

       [[12, 14, 16],
        [13, 15, 17]]])

In [210]:
stacked_array.shape

(3, 2, 3)

In [211]:
stacked_array = np.stack([ndarray_even, ndarray_odd], axis = 2)
stacked_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [212]:
stacked_array.shape

(3, 3, 2)

### np.traspose .T

In [214]:
#行と列を入れ替える
ndarray = np.random.randn(3, 4)
ndarray

array([[ 0.25214292,  1.822554  ,  0.15041605,  1.06790759],
       [ 0.25839637, -0.29716094,  0.06224103, -0.20029586],
       [-1.24294895, -1.14294512,  1.51890921, -0.3586147 ]])

In [215]:
ndarray.shape

(3, 4)

In [216]:
np.transpose(ndarray)

array([[ 0.25214292,  0.25839637, -1.24294895],
       [ 1.822554  , -0.29716094, -1.14294512],
       [ 0.15041605,  0.06224103,  1.51890921],
       [ 1.06790759, -0.20029586, -0.3586147 ]])

In [217]:
transepose_ndarray = _

In [219]:
transepose_ndarray

array([[ 0.25214292,  0.25839637, -1.24294895],
       [ 1.822554  , -0.29716094, -1.14294512],
       [ 0.15041605,  0.06224103,  1.51890921],
       [ 1.06790759, -0.20029586, -0.3586147 ]])

In [220]:
transepose_ndarray.shape

(4, 3)

In [221]:
#T = transposeの省略形
ndarray.T

array([[ 0.25214292,  0.25839637, -1.24294895],
       [ 1.822554  , -0.29716094, -1.14294512],
       [ 0.15041605,  0.06224103,  1.51890921],
       [ 1.06790759, -0.20029586, -0.3586147 ]])

In [222]:
ndarray.shape

(3, 4)

In [224]:
ndarray = np.random.randn(3, 4, 5)
ndarray

array([[[-0.09653541,  1.36040962,  2.32428613, -0.64887796,
         -0.61545343],
        [-1.39845975, -0.81684292,  0.34607775, -0.72782691,
          0.28850778],
        [-0.38249161, -2.93133993, -0.76172627,  1.4364264 ,
         -0.51297951],
        [ 0.76059212, -0.66313383,  1.10927902, -0.39567691,
         -1.42717912]],

       [[ 0.43688056, -0.16484717, -0.34025631,  0.04264195,
         -0.34667243],
        [ 1.57373675, -1.03181265,  1.54754325, -0.02535495,
         -0.78299218],
        [-1.1364169 , -1.83293124,  0.14268559,  1.9528989 ,
         -0.60034008],
        [ 0.72245551,  0.75892552, -1.27844356,  0.83831541,
          0.27490834]],

       [[-0.04160161,  0.46671481, -1.25909504,  1.13696613,
         -0.73557414],
        [-1.0192383 , -1.30909904,  1.67557969,  1.21507125,
          1.90909416],
        [ 0.36687312, -0.14013945,  0.58093048,  0.22004858,
         -1.1935705 ],
        [ 0.93413776, -1.45780329,  1.7601955 , -0.55505531,
          1

In [225]:
ndarray.shape

(3, 4, 5)

In [228]:
ndarray.T.shape

(5, 4, 3)

In [229]:
#１次元だった場合は何もしない
ndarray = np.random.randn(3)

In [231]:
ndarray

array([-0.2729902 , -0.85688184,  0.69722332])

In [232]:
ndarray.T

array([-0.2729902 , -0.85688184,  0.69722332])

In [233]:
np.transpose(ndarray)

array([-0.2729902 , -0.85688184,  0.69722332])

## NumPy arrayの保存とロード

### np.save('path', array)とnp.load('path')

In [4]:
ndarray = np.random.randn(3, 4, 5)
ndarray

array([[[-1.09152523,  0.92007054,  1.13117762,  0.56498564,
          1.11746386],
        [-0.98815411,  0.3043662 ,  0.54890922,  0.77750181,
         -0.29193435],
        [ 2.29623284,  0.38110906, -0.84971318,  1.66167805,
         -0.15241069],
        [ 0.60987638,  0.41112422,  0.04974514, -0.74121667,
          0.5073735 ]],

       [[-0.02647527, -0.18657759, -1.28447738,  0.22992825,
         -0.25595422],
        [ 0.57649815,  0.62074897, -2.58126184,  0.98820116,
          0.77879958],
        [-0.36203471, -0.84227242, -0.04613522, -1.59364204,
         -1.11321248],
        [ 0.17570742, -1.76167692,  0.27602501, -0.71040933,
          1.06136303]],

       [[ 0.61155865, -1.56940707,  0.86533984,  1.17560713,
          1.43587548],
        [ 1.90684107,  0.63210603,  1.26257084,  0.29688896,
         -0.46633471],
        [-0.8403859 , -0.53109847,  0.40290665,  0.17230314,
          0.76423916],
        [ 1.18818114, -1.72872653, -0.14440547,  0.60057322,
         -0

In [5]:
ndarray.shape

(3, 4, 5)

In [6]:
#パスは絶対パスでも相対パスでも可
np.save('sample_ndarray', ndarray)

In [8]:
loaded_ndarray = np.load('sample_ndarray.npy')
loaded_ndarray

array([[[-1.09152523,  0.92007054,  1.13117762,  0.56498564,
          1.11746386],
        [-0.98815411,  0.3043662 ,  0.54890922,  0.77750181,
         -0.29193435],
        [ 2.29623284,  0.38110906, -0.84971318,  1.66167805,
         -0.15241069],
        [ 0.60987638,  0.41112422,  0.04974514, -0.74121667,
          0.5073735 ]],

       [[-0.02647527, -0.18657759, -1.28447738,  0.22992825,
         -0.25595422],
        [ 0.57649815,  0.62074897, -2.58126184,  0.98820116,
          0.77879958],
        [-0.36203471, -0.84227242, -0.04613522, -1.59364204,
         -1.11321248],
        [ 0.17570742, -1.76167692,  0.27602501, -0.71040933,
          1.06136303]],

       [[ 0.61155865, -1.56940707,  0.86533984,  1.17560713,
          1.43587548],
        [ 1.90684107,  0.63210603,  1.26257084,  0.29688896,
         -0.46633471],
        [-0.8403859 , -0.53109847,  0.40290665,  0.17230314,
          0.76423916],
        [ 1.18818114, -1.72872653, -0.14440547,  0.60057322,
         -0

In [9]:
loaded_ndarray.shape

(3, 4, 5)

In [10]:
#ndarrayを単体で保存するのではなく、何か別の情報を付け加えて保存することが多い
#一旦dictionaryの形にして、それを保存する
dictionary = {
    'id': 123456,
    'image': ndarray
}

In [11]:
dictionary

{'id': 123456,
 'image': array([[[-1.09152523,  0.92007054,  1.13117762,  0.56498564,
           1.11746386],
         [-0.98815411,  0.3043662 ,  0.54890922,  0.77750181,
          -0.29193435],
         [ 2.29623284,  0.38110906, -0.84971318,  1.66167805,
          -0.15241069],
         [ 0.60987638,  0.41112422,  0.04974514, -0.74121667,
           0.5073735 ]],
 
        [[-0.02647527, -0.18657759, -1.28447738,  0.22992825,
          -0.25595422],
         [ 0.57649815,  0.62074897, -2.58126184,  0.98820116,
           0.77879958],
         [-0.36203471, -0.84227242, -0.04613522, -1.59364204,
          -1.11321248],
         [ 0.17570742, -1.76167692,  0.27602501, -0.71040933,
           1.06136303]],
 
        [[ 0.61155865, -1.56940707,  0.86533984,  1.17560713,
           1.43587548],
         [ 1.90684107,  0.63210603,  1.26257084,  0.29688896,
          -0.46633471],
         [-0.8403859 , -0.53109847,  0.40290665,  0.17230314,
           0.76423916],
         [ 1.18818114, -

In [12]:
np.save('sample_dict', dictionary)

In [17]:
#allow_pickle: False(省略可)
np.load('sample_dict.npy')

ValueError: Object arrays cannot be loaded when allow_pickle=False

In [28]:
#Pythonではオブジェクト、データを保存するときはpickleという形式で保存する
#今回のsample_dictもpickleで保存されている
#np.loadはpickleを直接ロードできないので、saveするときにallow_pickleを設定する必要がある
loaded_dict= np.load('sample_dict.npy', allow_pickle = True)

In [30]:
loaded_dict

array({'id': 123456, 'image': array([[[-1.09152523,  0.92007054,  1.13117762,  0.56498564,
          1.11746386],
        [-0.98815411,  0.3043662 ,  0.54890922,  0.77750181,
         -0.29193435],
        [ 2.29623284,  0.38110906, -0.84971318,  1.66167805,
         -0.15241069],
        [ 0.60987638,  0.41112422,  0.04974514, -0.74121667,
          0.5073735 ]],

       [[-0.02647527, -0.18657759, -1.28447738,  0.22992825,
         -0.25595422],
        [ 0.57649815,  0.62074897, -2.58126184,  0.98820116,
          0.77879958],
        [-0.36203471, -0.84227242, -0.04613522, -1.59364204,
         -1.11321248],
        [ 0.17570742, -1.76167692,  0.27602501, -0.71040933,
          1.06136303]],

       [[ 0.61155865, -1.56940707,  0.86533984,  1.17560713,
          1.43587548],
        [ 1.90684107,  0.63210603,  1.26257084,  0.29688896,
         -0.46633471],
        [-0.8403859 , -0.53109847,  0.40290665,  0.17230314,
          0.76423916],
        [ 1.18818114, -1.72872653, -0.1444

In [31]:
type(loaded_dict)

numpy.ndarray

In [36]:
#arrayの中にdictionaryがある
#NumPyでsaveすると、arrayで保存される
#後ろに [()] をつけてdictionaryを取り出す
#loadとセットで覚えておく
loaded_dict= np.load('sample_dict.npy', allow_pickle = True)[()]

In [37]:
loaded_dict

{'id': 123456,
 'image': array([[[-1.09152523,  0.92007054,  1.13117762,  0.56498564,
           1.11746386],
         [-0.98815411,  0.3043662 ,  0.54890922,  0.77750181,
          -0.29193435],
         [ 2.29623284,  0.38110906, -0.84971318,  1.66167805,
          -0.15241069],
         [ 0.60987638,  0.41112422,  0.04974514, -0.74121667,
           0.5073735 ]],
 
        [[-0.02647527, -0.18657759, -1.28447738,  0.22992825,
          -0.25595422],
         [ 0.57649815,  0.62074897, -2.58126184,  0.98820116,
           0.77879958],
         [-0.36203471, -0.84227242, -0.04613522, -1.59364204,
          -1.11321248],
         [ 0.17570742, -1.76167692,  0.27602501, -0.71040933,
           1.06136303]],
 
        [[ 0.61155865, -1.56940707,  0.86533984,  1.17560713,
           1.43587548],
         [ 1.90684107,  0.63210603,  1.26257084,  0.29688896,
          -0.46633471],
         [-0.8403859 , -0.53109847,  0.40290665,  0.17230314,
           0.76423916],
         [ 1.18818114, -

In [38]:
type(loaded_dict)

dict